# Generated by Django 3.2.9 on 2021-12-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cue_cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuecard',
            old_name='category_id',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
